name: ci/gh-actions/cli

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  schedule:
    - cron: '0 0 * * 1'

env:
  APT_INSTALL_LINUX: 'sudo apt update; sudo apt -y install git'
  APT_SET_CONF: |
        echo "Acquire::Retries       \"3\";"   | sudo tee -a /etc/apt/apt.conf.d/80-custom
        echo "Acquire::http::Timeout \"120\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
        echo "Acquire::ftp::Timeout  \"120\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: set apt conf
      run: ${{env.APT_SET_CONF}}
    - name: install dependencies
      run: ${{env.APT_INSTALL_LINUX}}
    - name: build
      run: ./ci.sh

